// Generate the site's blog data (web/src/lib/blog-content.js) from Nostr.
//
// Reads the author's NIP-23 kind-30023 events from relays and writes them in the
// SONAR_BLOG.posts shape the blog page + landing teaser already consume — so the
// relay is the delivery layer and the site prerenders whatever was published.
//
// Robust by design: if BLOG_NPUB is unset, the relay fetch errors, or it returns
// nothing, it falls back to the local docs/blog sources. A relay hiccup can
// therefore never ship an empty blog when posts exist in the repo.

import { SimplePool, useWebSocketImplementation } from 'nostr-tools/pool';
import { nip19 } from 'nostr-tools';
import WebSocket from 'ws';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPosts, buildArticle, eventToPost, publishedAt } from './lib.mjs';
import { RELAYS, BLOG_NPUB, ARTICLE_KIND } from './config.mjs';

useWebSocketImplementation(WebSocket);

const HERE = dirname(fileURLToPath(import.meta.url));
const BLOG_DIR = join(HERE, '..', '..', 'docs', 'blog');
const OUT = join(HERE, '..', '..', 'web', 'src', 'lib', 'blog-content.js');

/** Newest article per d-tag, mapped to the site post shape, newest first. */
function eventsToPosts(events) {
  const byD = new Map();
  for (const ev of events) {
    const d = ev.tags.find((t) => t[0] === 'd')?.[1];
    if (!d) continue;
    const cur = byD.get(d);
    if (!cur || ev.created_at > cur.created_at) byD.set(d, ev);
  }
  return [...byD.values()]
    .map(eventToPost)
    .filter(Boolean)
    .sort((a, b) => b._publishedAt - a._publishedAt);
}

/** Local docs/blog sources mapped to the site post shape (fallback path). */
function docsPosts() {
  return loadPosts(BLOG_DIR)
    .map((p) => eventToPost({ ...buildArticle(p), created_at: publishedAt(p.date) || 0 }))
    .filter(Boolean);
}

async function fromRelays() {
  if (!BLOG_NPUB) return null;
  let pubkey;
  try {
    const decoded = nip19.decode(BLOG_NPUB);
    pubkey = decoded.type === 'npub' ? decoded.data : null;
  } catch {
    pubkey = null;
  }
  if (!pubkey) {
    console.warn(`BLOG_NPUB is not a valid npub (${BLOG_NPUB}); using docs/blog.`);
    return null;
  }
  const pool = new SimplePool();
  try {
    const events = await pool.querySync(RELAYS, { kinds: [ARTICLE_KIND], authors: [pubkey] });
    const posts = eventsToPosts(events);
    return posts.length ? posts : null;
  } catch (e) {
    console.warn(`Relay fetch failed (${e?.message || e}); using docs/blog.`);
    return null;
  } finally {
    try {
      pool.close(RELAYS);
    } catch {
      /* ignore */
    }
  }
}

function writeModule(posts, source) {
  // Strip internal sort keys before serializing.
  const clean = posts.map(({ _publishedAt, ...p }) => p);
  const banner =
    `// AUTO-GENERATED by scripts/blog/fetch.mjs — do not edit by hand.\n` +
    `// Source: ${source}. Rendered by web/src/routes/blog/+page.svelte.\n`;
  writeFileSync(OUT, banner + 'export const SONAR_BLOG = ' + JSON.stringify({ posts: clean }, null, 2) + ';\n');
  console.log(`Wrote ${clean.length} post(s) to web/src/lib/blog-content.js (source: ${source}).`);
}

async function main() {
  const relayPosts = await fromRelays();
  if (relayPosts) {
    writeModule(relayPosts, `relays as ${BLOG_NPUB}`);
  } else {
    writeModule(docsPosts(), 'docs/blog/*/README.md (local fallback)');
  }
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
