import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import java.util.Properties

plugins {
    alias(libs.plugins.multiplatform)
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose)
    alias(libs.plugins.compose.compiler)
}

// Breez API key from a gitignored secret — NEVER hardcode or commit it.
// Resolution order: local.properties `breez.apiKey`, else env `BREEZ_API_KEY`,
// else empty (wallet UI then shows "unavailable", like iOS with no key).
val breezApiKey: String = run {
    val lp = rootProject.file("local.properties")
    val fromFile = if (lp.exists()) {
        Properties().apply { lp.inputStream().use { load(it) } }.getProperty("breez.apiKey")
    } else null
    (fromFile ?: System.getenv("BREEZ_API_KEY") ?: "").trim()
}

// Desktop has no Android-style BuildConfig, so the key is written to a generated
// resource (`/breez_api_key.txt`) the jvm WalletBridge reads at runtime. The dir
// is gitignored; the value never lands in source.
val breezKeyResDir = layout.buildDirectory.dir("generated/breezKey")
val generateBreezKeyResource = tasks.register("generateBreezKeyResource") {
    val out = breezKeyResDir.get().file("breez_api_key.txt").asFile
    inputs.property("breezApiKey", breezApiKey)
    outputs.file(out)
    doLast {
        out.parentFile.mkdirs()
        out.writeText(breezApiKey)
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // Desktop (macOS / Windows / Linux) via Compose Desktop. Default source-set
    // names are jvmMain/jvmTest. The same commonMain UI + SonarAppState drive it;
    // the Rust core is reached through the SAME UniFFI/JNA bindings as Android
    // (generated by core/build-desktop.sh into jvmMain) loading a host .dylib/.so.
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(libs.coroutines.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.coroutines.android)
            // On-device Lightning wallet (Breez SDK Liquid) for ⚡PAY.
            implementation(libs.breez.sdk.liquid)
            // UniFFI Kotlin bindings for the Rust core use JNA at runtime.
            // MUST be the @aar variant on Android — it ships libjnidispatch.so
            // as proper jniLibs (the plain jar hides it as a classpath resource
            // and you get UnsatisfiedLinkError).
            implementation("net.java.dev.jna:jna:5.14.0@aar")
        }
        val jvmMain by getting {
            // The desktop Breez API key is written here by `generateBreezKeyResource`
            // (gitignored generated dir), mirroring Android's BuildConfig field.
            resources.srcDir(breezKeyResDir)
            dependencies {
                implementation(compose.desktop.currentOs)
                // Swing/AWT EDT main dispatcher for Dispatchers.Main on desktop.
                implementation(libs.coroutines.swing)
                // On-device Lightning wallet (Breez SDK Liquid) for ⚡PAY — same
                // KMP artifact as Android; Gradle resolves its `jvm` variant (a
                // UniFFI/JNA binding). The host native lib (libbreez_sdk_liquid_
                // bindings.dylib) is fetched into jvmMain/resources by
                // core/build-desktop.sh, where JNA loads it off the classpath.
                implementation(libs.breez.sdk.liquid)
                // UniFFI Kotlin bindings load the host dynamic library via JNA.
                // Plain jar (the @aar variant is Android-only); the bundled
                // libjnidispatch ships in the jna jar for the desktop OS.
                implementation(libs.jna)
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "chat.bitchat.sonar.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Sonar"
            packageVersion = "1.0.0"
            description = "Sonar — Bluetooth mesh + Nostr secure messaging (desktop)"
            macOS {
                bundleID = "chat.bitchat.sonar.desktop"
                // Required so macOS shows the Bluetooth permission prompt for the
                // packaged app — the desktop BLE radio (sonar-ble / CoreBluetooth)
                // needs it. Without an .app bundle (e.g. `gradle run`) macOS can't
                // prompt, so BLE only works when the launching app already has the
                // Bluetooth grant.
                infoPlist {
                    extraKeysRawXml = """
                        <key>NSBluetoothAlwaysUsageDescription</key>
                        <string>Sonar uses Bluetooth to find people nearby and relay messages over the mesh.</string>
                    """.trimIndent()
                }
                // Under the hardened runtime, Bluetooth needs an entitlement (on
                // top of the Info.plist string) or macOS blocks it before prompting.
                // The file also carries the JVM's JIT + library-validation
                // entitlements (the app loads the Rust core/BLE dylibs at runtime).
                entitlementsFile.set(project.file("macos-entitlements.plist"))
                runtimeEntitlementsFile.set(project.file("macos-entitlements.plist"))
            }
        }
    }
}

// The jvm resources must carry the generated key file before packaging.
tasks.named("jvmProcessResources") { dependsOn(generateBreezKeyResource) }

android {
    namespace = "chat.bitchat.sonar"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "chat.bitchat.sonar.dev"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "0.1"
        buildConfigField("String", "BREEZ_API_KEY", "\"$breezApiKey\"")
    }

    buildFeatures {
        buildConfig = true
    }

    // The Rust core .so per ABI lives in src/androidMain/jniLibs (produced by
    // core/build-android.sh). Map it onto the Android main source set.
    sourceSets["main"].jniLibs.srcDirs("src/androidMain/jniLibs")

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
        getByName("debug") {
            // Debug builds only run on the local dev device. Both the Apple-
            // Silicon emulator and the Pixel 8 are arm64-v8a, so ship just that
            // ABI — keeps the debug APK small (the full multi-ABI build bundles
            // the Rust + Breez .so for every ABI and overflows small partitions).
            ndk { abiFilters += "arm64-v8a" }
        }
    }
}
