import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.gradle.api.tasks.Exec
import java.util.Properties

plugins {
    alias(libs.plugins.multiplatform)
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.google.services)
}

// Breez API key from a gitignored secret — NEVER hardcode or commit it.
// Resolution order: local.properties `breez.apiKey`, else env `BREEZ_API_KEY`,
// else empty (wallet UI then shows "unavailable", like iOS with no key).
val breezApiKey: String = run {
    val lp = rootProject.file("local.properties")
    val fromFile = if (lp.exists()) {
        Properties().apply { lp.inputStream().use { load(it) } }.getProperty("breez.apiKey")
    } else null
    (fromFile ?: System.getenv("BREEZ_API_KEY") ?: "").trim()
}

// Desktop has no Android-style BuildConfig, so the key is written to a generated
// resource (`/breez_api_key.txt`) the jvm WalletBridge reads at runtime. The dir
// is gitignored; the value never lands in source.
val breezKeyResDir = layout.buildDirectory.dir("generated/breezKey")
val generateBreezKeyResource = tasks.register("generateBreezKeyResource") {
    val out = breezKeyResDir.get().file("breez_api_key.txt").asFile
    inputs.property("breezApiKey", breezApiKey)
    outputs.file(out)
    doLast {
        out.parentFile.mkdirs()
        out.writeText(breezApiKey)
    }
}

val repoRootDir = rootProject.projectDir.parentFile.parentFile
val androidMainDir = layout.projectDirectory.dir("src/androidMain")
val androidBindingsFile = androidMainDir.file("kotlin/uniffi/sonar_ffi/sonar_ffi.kt")
val androidJniLibsDir = androidMainDir.dir("jniLibs")
val desktopMainDir = layout.projectDirectory.dir("src/jvmMain")
val desktopBindingsFile = desktopMainDir.file("kotlin/uniffi/sonar_ffi/sonar_ffi.kt")
val desktopResourcesDir = desktopMainDir.dir("resources")

val buildAndroidRustCore = tasks.register<Exec>("buildAndroidRustCore") {
    description = "Builds the Android Rust core and UniFFI Android bindings."
    group = "build"

    inputs.file(repoRootDir.resolve("core/build-android.sh"))
    inputs.file(repoRootDir.resolve("core/Cargo.toml"))
    inputs.file(repoRootDir.resolve("core/Cargo.lock"))
    inputs.dir(repoRootDir.resolve("core/sonar-core/src"))
    inputs.dir(repoRootDir.resolve("core/sonar-ffi/src"))
    outputs.file(androidBindingsFile)
    outputs.dir(androidJniLibsDir)

    workingDir(repoRootDir)
    commandLine(repoRootDir.resolve("core/build-android.sh").absolutePath)
}

val buildDesktopRustCore = tasks.register<Exec>("buildDesktopRustCore") {
    description = "Builds the desktop Rust core, BLE bridge, native wallet lib, and UniFFI JVM bindings."
    group = "build"

    inputs.file(repoRootDir.resolve("core/build-desktop.sh"))
    inputs.file(repoRootDir.resolve("core/Cargo.toml"))
    inputs.file(repoRootDir.resolve("core/Cargo.lock"))
    inputs.file(repoRootDir.resolve("core/sonar-ble/Cargo.toml"))
    inputs.dir(repoRootDir.resolve("core/sonar-core/src"))
    inputs.dir(repoRootDir.resolve("core/sonar-ffi/src"))
    inputs.dir(repoRootDir.resolve("core/sonar-ble/src"))
    inputs.file(rootProject.file("gradle/libs.versions.toml"))
    outputs.file(desktopBindingsFile)
    outputs.dir(desktopResourcesDir)

    workingDir(repoRootDir)
    commandLine(repoRootDir.resolve("core/build-desktop.sh").absolutePath)
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    // Desktop (macOS / Windows / Linux) via Compose Desktop. Default source-set
    // names are jvmMain/jvmTest. The same commonMain UI + SonarAppState drive it;
    // the Rust core is reached through the SAME UniFFI/JNA bindings as Android
    // (generated by core/build-desktop.sh into jvmMain) loading a host .dylib/.so.
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(libs.coroutines.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.coroutines.android)
            // On-device Lightning wallet (Breez SDK Liquid) for ⚡PAY.
            implementation(libs.breez.sdk.liquid)
            // UniFFI Kotlin bindings for the Rust core use JNA at runtime.
            // MUST be the @aar variant on Android — it ships libjnidispatch.so
            // as proper jniLibs (the plain jar hides it as a classpath resource
            // and you get UnsatisfiedLinkError).
            implementation("net.java.dev.jna:jna:5.14.0@aar")
            // QR encoding for shareable group invite links.
            implementation("com.google.zxing:core:3.5.3")
        }
        val jvmMain by getting {
            // The desktop Breez API key is written here by `generateBreezKeyResource`
            // (gitignored generated dir), mirroring Android's BuildConfig field.
            resources.srcDir(breezKeyResDir)
            dependencies {
                implementation(compose.desktop.currentOs)
                // Swing/AWT EDT main dispatcher for Dispatchers.Main on desktop.
                implementation(libs.coroutines.swing)
                // On-device Lightning wallet (Breez SDK Liquid) for ⚡PAY — same
                // KMP artifact as Android; Gradle resolves its `jvm` variant (a
                // UniFFI/JNA binding). The host native lib (libbreez_sdk_liquid_
                // bindings.dylib) is fetched into jvmMain/resources by
                // core/build-desktop.sh, where JNA loads it off the classpath.
                implementation(libs.breez.sdk.liquid)
                // UniFFI Kotlin bindings load the host dynamic library via JNA.
                // Plain jar (the @aar variant is Android-only); the bundled
                // libjnidispatch ships in the jna jar for the desktop OS.
                implementation(libs.jna)
                // QR encoding for shareable group invite links.
                implementation("com.google.zxing:core:3.5.3")
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "chat.bitchat.sonar.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Sonar"
            packageVersion = "1.0.0"
            description = "Sonar — Bluetooth mesh + Nostr secure messaging (desktop)"
            macOS {
                bundleID = "chat.bitchat.sonar.desktop"
                // Reuse the Android launcher icon (sonar rings on #0A1418),
                // rendered 1:1 to .icns so the Mac app matches the phone.
                iconFile.set(project.file("sonar.icns"))
                // Required so macOS shows the Bluetooth permission prompt for the
                // packaged app — the desktop BLE radio (sonar-ble / CoreBluetooth)
                // needs it. Without an .app bundle (e.g. `gradle run`) macOS can't
                // prompt, so BLE only works when the launching app already has the
                // Bluetooth grant.
                infoPlist {
                    extraKeysRawXml = """
                        <key>NSBluetoothAlwaysUsageDescription</key>
                        <string>Sonar uses Bluetooth to find people nearby and relay messages over the mesh.</string>
                    """.trimIndent()
                }
                // Under the hardened runtime, Bluetooth needs an entitlement (on
                // top of the Info.plist string) or macOS blocks it before prompting.
                // The file also carries the JVM's JIT + library-validation
                // entitlements (the app loads the Rust core/BLE dylibs at runtime).
                entitlementsFile.set(project.file("macos-entitlements.plist"))
                runtimeEntitlementsFile.set(project.file("macos-entitlements.plist"))
            }
        }
    }
}

// The jvm resources must carry the generated key file before packaging.
tasks.named("jvmProcessResources") { dependsOn(generateBreezKeyResource) }
tasks.named("compileKotlinJvm") { dependsOn(buildDesktopRustCore) }
tasks.named("jvmProcessResources") { dependsOn(buildDesktopRustCore) }
tasks.named("preBuild") { dependsOn(buildAndroidRustCore) }

android {
    namespace = "chat.bitchat.sonar"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "chat.bitchat.sonar"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 4
        versionName = "0.0.1-alpha.4"
        buildConfigField("String", "BREEZ_API_KEY", "\"$breezApiKey\"")
        val lp = Properties().apply {
            val f = rootProject.file("local.properties")
            if (f.exists()) f.inputStream().use { load(it) }
        }
        buildConfigField("String", "TRANSPONDER_NPUB",
            "\"${lp.getProperty("sonar.transponder.npub", "")}\"")
        buildConfigField("String", "NDS_URL",
            "\"${lp.getProperty("sonar.nds.url", "")}\"")
    }

    buildFeatures {
        buildConfig = true
    }

    // The Rust core .so per ABI lives in src/androidMain/jniLibs (produced by
    // core/build-android.sh). Map it onto the Android main source set.
    sourceSets["main"].jniLibs.srcDirs("src/androidMain/jniLibs")

    packaging {
        jniLibs {
            pickFirsts += listOf("lib/*/libc++_shared.so")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
        getByName("debug") {
            // Debug builds only run on the local dev device. Both the Apple-
            // Silicon emulator and the Pixel 8 are arm64-v8a, so ship just that
            // ABI — keeps the debug APK small (the full multi-ABI build bundles
            // the Rust + Breez .so for every ABI and overflows small partitions).
            ndk { abiFilters += "arm64-v8a" }
        }
    }
}

dependencies {
    // Firebase Cloud Messaging for push wakeups (transponder + Breez NDS).
    // platform() BOM isn't supported inside KMP's androidMain.dependencies {},
    // so Firebase goes through the standard Gradle dependencies block.
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.messaging)
}
