// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sonar_ffiFFI)
import sonar_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sonar_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sonar_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSonarFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A Nostr identity (secp256k1 keypair). Wraps `sonar_core::identity::Identity`.
 */
public protocol SonarIdentityProtocol: AnyObject, Sendable {
    
    /**
     * `npub1...` form of the public key.
     */
    func npub()  -> String
    
    /**
     * `nsec1...` secret key export (user-driven backup only).
     */
    func nsec()  -> String
    
    /**
     * 64-char lowercase hex public key.
     */
    func pubkeyHex()  -> String
    
}
/**
 * A Nostr identity (secp256k1 keypair). Wraps `sonar_core::identity::Identity`.
 */
open class SonarIdentity: SonarIdentityProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_sonar_ffi_fn_clone_sonaridentity(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_sonar_ffi_fn_free_sonaridentity(handle, $0) }
    }

    
    /**
     * Generate a brand-new identity (default onboarding path).
     */
public static func generate() -> SonarIdentity  {
    return try!  FfiConverterTypeSonarIdentity_lift(try! rustCall() {
    uniffi_sonar_ffi_fn_constructor_sonaridentity_generate($0
    )
})
}
    
    /**
     * Import from an `nsec1...` bech32 string or 64-char hex secret key.
     */
public static func `import`(nsec: String)throws  -> SonarIdentity  {
    return try  FfiConverterTypeSonarIdentity_lift(try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_constructor_sonaridentity_import(
        FfiConverterString.lower(nsec),$0
    )
})
}
    

    
    /**
     * `npub1...` form of the public key.
     */
open func npub() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sonar_ffi_fn_method_sonaridentity_npub(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * `nsec1...` secret key export (user-driven backup only).
     */
open func nsec() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sonar_ffi_fn_method_sonaridentity_nsec(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * 64-char lowercase hex public key.
     */
open func pubkeyHex() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sonar_ffi_fn_method_sonaridentity_pubkey_hex(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSonarIdentity: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SonarIdentity

    public static func lift(_ handle: UInt64) throws -> SonarIdentity {
        return SonarIdentity(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SonarIdentity) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SonarIdentity {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SonarIdentity, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSonarIdentity_lift(_ handle: UInt64) throws -> SonarIdentity {
    return try FfiConverterTypeSonarIdentity.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSonarIdentity_lower(_ value: SonarIdentity) -> UInt64 {
    return FfiConverterTypeSonarIdentity.lower(value)
}






/**
 * A relay-connected Sonar node. Owns its own tokio runtime; every method is
 * blocking — call from a background queue in Swift, never the main thread.
 */
public protocol SonarNodeProtocol: AnyObject, Sendable {
    
    /**
     * All groups this identity belongs to.
     */
    func groups() throws  -> [GroupInfo]
    
    /**
     * Decrypted message history for a group, oldest first.
     */
    func messages(groupIdHex: String) throws  -> [MessageInfo]
    
    /**
     * Publish our kind-30443 KeyPackage so others can start groups with us.
     */
    func publishKeyPackage() throws 
    
    /**
     * Encrypt + publish a text message to the group.
     */
    func sendText(groupIdHex: String, text: String) throws 
    
    /**
     * Start a 1:1 DM group with `peer` (npub or hex pubkey). Fetches their
     * KeyPackage from the relays and delivers the welcome. Returns the new
     * group id as hex.
     */
    func startDm(peer: String, name: String) throws  -> String
    
    /**
     * Poll the relays once: welcomes addressed to us, then group messages.
     */
    func syncOnce() throws 
    
}
/**
 * A relay-connected Sonar node. Owns its own tokio runtime; every method is
 * blocking — call from a background queue in Swift, never the main thread.
 */
open class SonarNode: SonarNodeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_sonar_ffi_fn_clone_sonarnode(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_sonar_ffi_fn_free_sonarnode(handle, $0) }
    }

    
    /**
     * Connect `identity` to the given relays (e.g. `wss://relay.damus.io`) with
     * a persistent, encrypted SQLCipher store.
     *
     * - `db_path`: absolute filesystem path for the database (the Swift host
     * passes e.g. `<Application Support>/sonar-marmot/marmot.sqlite`; the host
     * must create the parent directory, ideally Data-Protection-Complete).
     * - `db_key_hex`: 64-char hex of the 32-byte SQLCipher key. The host owns
     * this key (Keychain on iOS) and passes the SAME value every launch so the
     * existing database reopens. Marmot groups/messages persist across restarts.
     */
public static func connect(identity: SonarIdentity, relayUrls: [String], dbPath: String, dbKeyHex: String)throws  -> SonarNode  {
    return try  FfiConverterTypeSonarNode_lift(try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_constructor_sonarnode_connect(
        FfiConverterTypeSonarIdentity_lower(identity),
        FfiConverterSequenceString.lower(relayUrls),
        FfiConverterString.lower(dbPath),
        FfiConverterString.lower(dbKeyHex),$0
    )
})
}
    

    
    /**
     * All groups this identity belongs to.
     */
open func groups()throws  -> [GroupInfo]  {
    return try  FfiConverterSequenceTypeGroupInfo.lift(try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_method_sonarnode_groups(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Decrypted message history for a group, oldest first.
     */
open func messages(groupIdHex: String)throws  -> [MessageInfo]  {
    return try  FfiConverterSequenceTypeMessageInfo.lift(try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_method_sonarnode_messages(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(groupIdHex),$0
    )
})
}
    
    /**
     * Publish our kind-30443 KeyPackage so others can start groups with us.
     */
open func publishKeyPackage()throws   {try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_method_sonarnode_publish_key_package(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Encrypt + publish a text message to the group.
     */
open func sendText(groupIdHex: String, text: String)throws   {try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_method_sonarnode_send_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(groupIdHex),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * Start a 1:1 DM group with `peer` (npub or hex pubkey). Fetches their
     * KeyPackage from the relays and delivers the welcome. Returns the new
     * group id as hex.
     */
open func startDm(peer: String, name: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_method_sonarnode_start_dm(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(peer),
        FfiConverterString.lower(name),$0
    )
})
}
    
    /**
     * Poll the relays once: welcomes addressed to us, then group messages.
     */
open func syncOnce()throws   {try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_method_sonarnode_sync_once(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSonarNode: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SonarNode

    public static func lift(_ handle: UInt64) throws -> SonarNode {
        return SonarNode(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SonarNode) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SonarNode {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SonarNode, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSonarNode_lift(_ handle: UInt64) throws -> SonarNode {
    return try FfiConverterTypeSonarNode.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSonarNode_lower(_ value: SonarNode) -> UInt64 {
    return FfiConverterTypeSonarNode.lower(value)
}




/**
 * FFI-friendly group summary.
 */
public struct GroupInfo: Equatable, Hashable {
    /**
     * Hex of the MLS group id (stable; use it for `send_text`/`messages`).
     */
    public var idHex: String
    public var name: String
    public var memberNpubs: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex of the MLS group id (stable; use it for `send_text`/`messages`).
         */idHex: String, name: String, memberNpubs: [String]) {
        self.idHex = idHex
        self.name = name
        self.memberNpubs = memberNpubs
    }

    

    
}

#if compiler(>=6)
extension GroupInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGroupInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GroupInfo {
        return
            try GroupInfo(
                idHex: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                memberNpubs: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: GroupInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.idHex, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterSequenceString.write(value.memberNpubs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroupInfo_lift(_ buf: RustBuffer) throws -> GroupInfo {
    return try FfiConverterTypeGroupInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroupInfo_lower(_ value: GroupInfo) -> RustBuffer {
    return FfiConverterTypeGroupInfo.lower(value)
}


/**
 * FFI-friendly decrypted chat message.
 */
public struct MessageInfo: Equatable, Hashable {
    public var idHex: String
    public var senderNpub: String
    public var content: String
    public var createdAtSecs: UInt64
    /**
     * True when the local identity sent it.
     */
    public var mine: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(idHex: String, senderNpub: String, content: String, createdAtSecs: UInt64, 
        /**
         * True when the local identity sent it.
         */mine: Bool) {
        self.idHex = idHex
        self.senderNpub = senderNpub
        self.content = content
        self.createdAtSecs = createdAtSecs
        self.mine = mine
    }

    

    
}

#if compiler(>=6)
extension MessageInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageInfo {
        return
            try MessageInfo(
                idHex: FfiConverterString.read(from: &buf), 
                senderNpub: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                createdAtSecs: FfiConverterUInt64.read(from: &buf), 
                mine: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MessageInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.idHex, into: &buf)
        FfiConverterString.write(value.senderNpub, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterUInt64.write(value.createdAtSecs, into: &buf)
        FfiConverterBool.write(value.mine, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageInfo_lift(_ buf: RustBuffer) throws -> MessageInfo {
    return try FfiConverterTypeMessageInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageInfo_lower(_ value: MessageInfo) -> RustBuffer {
    return FfiConverterTypeMessageInfo.lower(value)
}


/**
 * Flat error: only the rendered message crosses the FFI boundary
 * (`SonarFfiError.InvalidInput(message:)` / `.Core(message:)` in Swift).
 */
public enum SonarFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Caller passed something unparseable (bad nsec, npub, hex, relay URL).
     */
    case InvalidInput(message: String)
    
    /**
     * Anything that went wrong inside sonar-core (relay I/O, MLS, MDK...).
     */
    case Core(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension SonarFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSonarFfiError: FfiConverterRustBuffer {
    typealias SwiftType = SonarFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SonarFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Core(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SonarFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Core(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSonarFfiError_lift(_ buf: RustBuffer) throws -> SonarFfiError {
    return try FfiConverterTypeSonarFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSonarFfiError_lower(_ value: SonarFfiError) -> RustBuffer {
    return FfiConverterTypeSonarFfiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGroupInfo: FfiConverterRustBuffer {
    typealias SwiftType = [GroupInfo]

    public static func write(_ value: [GroupInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGroupInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GroupInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [GroupInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGroupInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessageInfo: FfiConverterRustBuffer {
    typealias SwiftType = [MessageInfo]

    public static func write(_ value: [MessageInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessageInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MessageInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [MessageInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessageInfo.read(from: &buf))
        }
        return seq
    }
}
/**
 * Erase the persistent Marmot database at `db_path` (and its SQLite sidecars:
 * `-wal`, `-shm`, `-journal`).
 *
 * Panic-wipe entry point. Call when NO `SonarNode` holds that path open (drop
 * the node first). The Swift host should also clear the Keychain-held DB key.
 * Idempotent: a missing file is not an error.
 */
public func wipeMarmotDatabase(dbPath: String)throws   {try rustCallWithError(FfiConverterTypeSonarFfiError_lift) {
    uniffi_sonar_ffi_fn_func_wipe_marmot_database(
        FfiConverterString.lower(dbPath),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sonar_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sonar_ffi_checksum_func_wipe_marmot_database() != 5401) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonaridentity_npub() != 62373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonaridentity_nsec() != 31744) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonaridentity_pubkey_hex() != 4949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonarnode_groups() != 48990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonarnode_messages() != 63355) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonarnode_publish_key_package() != 48211) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonarnode_send_text() != 23173) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonarnode_start_dm() != 11780) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_method_sonarnode_sync_once() != 45718) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_constructor_sonaridentity_generate() != 7736) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_constructor_sonaridentity_import() != 46969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sonar_ffi_checksum_constructor_sonarnode_connect() != 2559) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSonarFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all